# Sponsor button at the top of the repo.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - 'https://pay.cloudtips.ru/p/6c077990'
  - 'https://boosty.to/jsu/donate'
